name: Openwrt Test Variable
on:
#  push:
#    branches: master
  [workflow_dispatch]
env:
  OWRT_RELEASE: 22.03.2
  OWRT_TARGET: x86
  OWRT_SUBTARGET: 64
  OWRT_SDK_VERSION: 11.2.0

jobs:
  buildpkg:
    name: Test Package Variable
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        SDK_URL:
        - https://downloads.openwrt.org/releases/$OWRT_RELEASE/targets/$OWRT_TARGET/$OWRT_SUBTARGET/openwrt-sdk-$OWRT_RELEASE-$OWRT_TARGET-$OWRT_SUBTARGET_gcc-$OWRT_SDK_VERSION_musl.Linux-$OWRT_TARGET_$OWRT_SUBTARGET.tar.xz
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
    - uses: actions/checkout@master
    - name: Assemble Variable
      run: |
        DEFAULT_PACKAGES=$(wget -qO - https://downloads.openwrt.org/releases/$OWRT_RELEASE/targets/$OWRT_TARGET/$OWRT_SUBTARGET/openwrt-$OWRT_RELEASE-$OWRT_TARGET-$OWRT_SUBTARGET.manifest | sed  's/ - .*/ /' | \
                        sed 's/dnsmasq//g; s/kmod-e1000\ //g; s/kmod-ppp\ //g; s/kmod-pppoe\ //g; s/kmod-ppox\ //g; s/luci-proto-ppp//g; s/ppp\ //g; s/ppp-mod-pppoe//g; s/kmod-e1000e//g' | tr '\n' ' ')
        echo $DEFAULT_PACKAGES
        echo "=============================="
        FINAL_PACKAGE_LIST="$DEFAULT_PACKAGES \
          -luci-ssl -dnsmasq dnsmasq-full lm-sensors-detect bash curl diffutils jq luci-app-openvpn \
          luci-proto-qmi fdisk mosquitto-client-nossl mosquitto-nossl unzip usb-modeswitch \
          adblock e2fsprogs jsonfilter luci-app-adblock partx-utils r8169-firmware iperf3 mbim-utils qmi-utils \
          libmbim libqmi modemmanager luci-proto-modemmanager ppp nano openvpn-openssl \
          luci-ssl-openssl luci-app-commands ca-bundle ca-certificates pciutils usbutils rsync ipset mtr lscpu \
          luci-proto-wireguard luci-app-wireguard wireguard-tools \
          kmod-usb-hid kmod-usb3 kmod-usb2 -dnscrypt-proxy -kmod-e1000 kmod-r8169 \
          kmod-hwmon-core kmod-lib-crc-itu-t kmod-libphy kmod-natsemi kmod-ne2k-pci usbutils pciutils \
          kmod-usb-net-sierrawireless kmod-usb-serial-sierrawireless kmod-usb-serial-qualcomm \
          kmod-usb-net-cdc-ether kmod-usb-net-cdc-mbim kmod-usb-net-cdc-ncm kmod-usb-net-hso msmtp sysfsutils \
          kmod-usb-net-qmi-wwan kmod-usb-serial kmod-usb-serial-option kmod-usb-serial-wwan gdb jq jsonfilter speedtest-netperf \
          -ddns-scripts -ddns-scripts_no-ip_com -ext-samba -ext-sms -kmod-e1000 -kmod-i2c-algo-bit memcached foolsm \
          -kmod-i2c-core -kmod-ppp -kmod-pppoe -kmod-pppox -ppp-mod-pppoe -kmod-e1000e -kmod-usb-net-huawei-cdc-ncm \
          -libsodium -libustream-mbedtls -libustream-wolfssl -luci-app-hotspot \
          -luci-app-samba -luci-proto-ppp -luci-theme-bootstrap -luci-theme-darkmatter -mwan3 -ntfs-3g -px5g-mbedtls \
          -p910nd -luci-app-p910nd -ext-p910nd -samba36-server -wireless-tools -wpad-mini -wwan"
        echo $FINAL_PACKAGE_LIST
      
